services:

  postgres:
    image: postgres:16-alpine
    container_name: taskflow-db-k8s
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_DB: taskflow
      POSTGRES_USER: taskflow
      POSTGRES_PASSWORD: taskflow_secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskflow -d taskflow"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata: